supported tenant api
payjp/payjp-ruby pull request #19
Opened 2020-07-19 12:38 UTC by cobafan

[docs](http://u0u0.net/QIS3)

I couldn't find a class that supports the Tenant API.

I resolved only CRUD endpoint for Tenant API.

Could you consider this Pull Request?

2020-10-06 07:49 UTC, hiromi2424 commented
In addition, that class also should include:

```ruby
    def generate_application_url
      response = request(:post, application_url)
      response
    end

    private

    def application_url
      url + '/application_urls'
    end
```

2022-08-17 05:48 UTC, natsuki-yamanaka requested changes

2022-08-17 05:48 UTC, natsuki-yamanaka commented on test/payjp/tenant_test.jp
> +require File.expand_path('../../test_helper', __FILE__)
ファイル名が `tenant_test.jp` になっておりテスト対象となっていませんでした。
また、.rbに直してローカルでテストを実行してみたところ下記で失敗していました
```
     29:     should "create should return a new tenant" do
     30:       @mock.expects(:post).once.returns(test_response(test_tenant))
     31:       t = Payjp::Tenant.create
  => 32:       assert_equal "t_test_tenant", t.id
     33:     end
     34:   end
     35: end
test/payjp/tenant_test.rb:32:in `block in <class:TenantTest>'
<"t_test_tenant"> expected but was
<"test">

diff:
? t_test_tenant
Failure: test: create should return a new tenant(Payjp::TenantTest)

      6:       @mock.expects(:get).once.returns(test_response(test_tenant_array))
      7:       t = Payjp::Tenant.all.data
      8:       assert t.is_a? Array
  =>  9:       assert t[0].is_a? Payjp::Tenant
     10:     end
     11:
     12:     should "tenants should be deletable" do
test/payjp/tenant_test.rb:9:in `block in <class:TenantTest>'
Failure: test: tenants should be listable(Payjp::TenantTest): <false> is not true.
```

2022-08-17 08:38 UTC, natsuki-yamanaka commented
https://github.com/payjp/payjp-ruby/pull/24
こちらに引き継ぐためクローズさせていただきます。

2022-08-17 08:38 UTC, closed without merging